# Site settings
title: Breezy
email: your-email@domain.com
baseurl: ""
url: "http://daffl.github.io/breezy"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude:
  - "node_modules"
